### ISSUE TITLE
 What is the Sensitive API？

### ISSUE THREAD

**Issue by 17826875910** [malscan-android/MalScan#1]
Hi, Thank you for reading.
I have one quesion about the sensitive api.
you have mentioned ` inorder to characterize malicious behaviors, we focus on these security-related API calls, namely sensitive API calls on the basis of the results reported by PScout [24] which consist of 21,986 sensitive API calls.` , but I can't find the sensitive api list . Could you provide the list or  the method？

**Comment by malscan-android** [comment]
Hello! We have uploaded the list of sensitive API calls used in our paper.

**Comment by 17826875910** [comment]
Thanks for  your reply and share.

**Comment by wudaoshengtian** [comment]
do you have this problem ？
python3 Classification.py -d /home/ubuntu/MalScan-code/out22 -o /home/ubuntu/MalScan-code/out33 -t degree
Traceback (most recent call last):
  File "Classification.py", line 290, in <module>
    main()
  File "Classification.py", line 259, in main
    degree_csv_data = classification(degree_vectors, degree_labels)
  File "Classification.py", line 232, in classification
    csv_data[1].extend(knn_1(Vectors, Labels))
  File "Classification.py", line 85, in knn_1
    for train_index, test_index in kf.split(X):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sklearn/model_selection/_split.py", line 333, in split
    raise ValueError(
ValueError: Cannot have number of splits n_splits=10 greater than the number of samples: n_samples=0.

**Comment by wudaoshengtian** [comment]
It would be greatly appreciated if you could help me
